name: hardhat test

on:
  push:
    branches: [ gulpTests ]
  pull_request:
    branches: [ gulpTests ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14.17.1
      - name: install modules
        run: npm install
      - name: install ganache
        run: npm install ganache-cli
      - name: start ganache
        run: node_modules/.bin/ganache-cli --port 8545 -a 100 &
      - name: install hardhat
        run: |
          npm install hardhat
          node_modules/.bin/hardhat version
      - name: execute hardhat test
        run: node_modules/.bin/hardhat test --network test
          
