name: Hardhat Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
      run: |
            npm install
    - name: Installing hardhat
      run : | 
            npm install --save-dev @nomiclabs/hardhat-ganache
            npm install --save-dev hardhat
            npm install --save-dev '@nomiclabs/hardhat-waffle'
            npm install --save-dev "@nomiclabs/hardhat-ethers@^2.0.0" "ethers@^5.0.0" "ethereum-waffle@^3.2.0"
            npm install --save-dev chai
            npm install --save-dev "@nomiclabs/hardhat-ethers": "^2.0.0", "@nomiclabs/hardhat-etherscan": "^2.1.1",
                                                                          "@nomiclabs/hardhat-waffle": "^2.0.1",
                                                                          "@typechain/ethers-v5": "^7.0.1",
                                                                          "@typechain/hardhat": "^2.1.2",
                                                                          "@types/chai": "^4.2.21",
                                                                          "@types/mocha": "^8.2.3",
                                                                          "@types/node": "^16.3.0",
                                                                          "chai": "^4.3.4",
                                                                          "ethereum-waffle": "^3.2.0",
                                                                          "ethers": "^5.0.0",
                                                                          "hardhat": "^2.0.8",
                                                                          "ts-node": "^10.0.0",
                                                                          "typechain": "^5.1.1",
                                                                          "typescript": "^4.3.5"
    - name: testing using hardhat
      run : |
            npx hardhat test
            
