name: Hardhat Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build
      run: |
            yarn install
    - name: Installing hardhat
      run : | 
            npm install --save-dev @nomiclabs/hardhat-ganache
            npm install --save-dev hardhat
            npm install --save-dev '@nomiclabs/hardhat-waffle'
            npm install --save-dev "@nomiclabs/hardhat-ethers@^2.0.0" "ethers@^5.0.0" "ethereum-waffle@^3.2.0"
            npm install --save-dev chai
            npm install --save-dev "@nomiclabs/hardhat-ethers" "@nomiclabs/hardhat-etherscan" "@nomiclabs/hardhat-waffle"
            npm install --save-dev "@typechain/ethers-v5" "@typechain/hardhat" "@types/chai" "@types/mocha" "@types/node" "ethereum-waffle" "ethers" "hardhat" "ts-node" "typechain" "typescript"
            npm install --save-dev "@nomiclabs/buidler-web3" "@nomiclabs/hardhat-web3" "@openzeppelin/contracts" "@openzeppelin/test-helpers" "@uniswap/v3-periphery" "bignumber.js" "dotenv" "eslint"
            yarn add --dev hardhat-contract-sizer
    - name: testing using hardhat
      run : |
            npx hardhat compile
            npx hardhat test
            
